import { useState } from 'react'
import { MoreVertical, Layout, Plus, Wand2, Type, Check, ChevronDown, BarChart2, Box, RefreshCw } from 'lucide-react'
import { SlidePreview } from '#/features/presentations/components/slide-preview'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { updateSlideLayout, updateSlideContent, deleteSlide, deleteSlideImage } from '#/features/presentations/actions/slide-mutations'
import { partialEditWithAI } from '#/features/presentations/actions/ai-partial-edit'
import { editSlideWithAI, regenerateImageOnly } from '#/features/presentations/actions/ai-edit-actions'
import { useTextSelection } from './hooks/use-text-selection'
import { TextSelectionToolbar } from './TextSelectionToolbar'
import { toast } from 'sonner'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '#/components/ui/dropdown-menu'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '#/components/ui/alert-dialog'
import { Trash2, Edit2 } from 'lucide-react'
import type { BlockType } from '#/features/templates/types'

interface SlideEditorProps {
  slide: {
    id: string
    title: string
    content: string
    imageUrl?: string | null
    order: number
    layoutType?: string | null
  }
  index: number
  isActive: boolean
  template?: any
  isImported?: boolean
  presentationId: string
  isAiEditing?: boolean
}

const LAYOUTS: { type: BlockType; label: string; icon: any }[] = [
  { type: 'hero', label: 'Hero', icon: <Wand2 className="size-4" /> },
  { type: 'title-content', label: 'Title & Content', icon: <Type className="size-4" /> },
  { type: 'two-column', label: 'Two Column', icon: <Layout className="size-4" /> },
  { type: 'stats', label: 'Stats Grid', icon: <BarChart2 className="size-4" /> },
  { type: 'quote', label: 'Quote', icon: <Check className="size-4" /> },
  { type: 'cta', label: 'Call to Action', icon: <Box className="size-4" /> },
]

export function SlideEditor({ slide, index, isActive, template, isImported, presentationId, isAiEditing }: SlideEditorProps) {
  const queryClient = useQueryClient()
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  
  const layoutMut = useMutation({
    mutationFn: (layoutType: string) => updateSlideLayout({ slideId: slide.id, layoutType }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations', 'detail', presentationId] })
      toast.success('Layout updated')
    },
    onError: (err: any) => toast.error(err.message || 'Layout update failed')
  })

  const contentMut = useMutation({
    mutationFn: (data: { title?: string; content?: string }) => 
      updateSlideContent({ slideId: slide.id, ...data }),
    onMutate: () => {
      toast.loading('Saving changes...', { id: 'slide-save' })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations', 'detail', presentationId] })
      toast.success('Saved', { id: 'slide-save' })
    },
    onError: (err: any) => {
      toast.error(err.message || 'Failed to save', { id: 'slide-save' })
    }
  })

  const selection = useTextSelection()

  const aiPartialMut = useMutation({
    mutationFn: (prompt: string) => partialEditWithAI({
      data: {
        slideId: slide.id,
        selection: selection.text,
        prompt,
        fullContent: slide.content, 
        field: 'content'
      }
    }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations'] })
      toast.success('AI Rewrite applied')
    },
    onError: (err: any) => toast.error(err.message || 'AI Rewrite failed')
  })

  const aiRegenMut = useMutation({
    mutationFn: (prompt: string) => editSlideWithAI({
      data: {
        slideId: slide.id,
        prompt
      }
    }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations', 'detail', presentationId] })
      toast.success('Slide regenerated by AI')
    },
    onError: (err: any) => toast.error(err.message || 'Regeneration failed')
  })

  const imgRegenMut = useMutation({
    mutationFn: (prompt: string) => regenerateImageOnly({
      data: {
        slideId: slide.id,
        prompt
      }
    }),
    onMutate: () => {
      toast.loading('AI is generating a new image...', { id: 'img-regen' })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations', 'detail', presentationId] })
      toast.success('Image regenerated', { id: 'img-regen' })
    },
    onError: (err: any) => toast.error(err.message || 'Image generation failed', { id: 'img-regen' })
  })

  const imgDeleteMut = useMutation({
    mutationFn: () => deleteSlideImage({ data: { slideId: slide.id } }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations', 'detail', presentationId] })
      toast.success('Image removed')
    },
    onError: (err: any) => toast.error(err.message || 'Image deletion failed')
  })

  const deleteMut = useMutation({
    mutationFn: () => deleteSlide({ data: { slideId: slide.id } }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['presentations'] })
      toast.success('Slide deleted')
    },
    onError: (err: any) => toast.error(err.message || 'Delete failed')
  })

  const handleLayoutSelect = (type: BlockType) => {
    layoutMut.mutate(type)
  }

  return (
    <div className={`relative w-full max-w-4xl mx-auto mb-20 transition-all duration-500 ${
       isActive ? 'opacity-100 scale-100 z-10' : 'opacity-40 scale-[0.98] z-0'
    }`}>
      {/* Slide Toolbar */}
      <div className="absolute -top-12 left-0 flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity z-20">
         <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-bgDark1 border border-white/10 text-white text-xs font-bold hover:bg-white/5 transition-all shadow-xl">
                 <Layout className="size-3.5 text-indigo-400" />
                 {LAYOUTS.find(l => l.type === slide.layoutType)?.label || 'Auto Layout'}
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" className="bg-bgDark1 border-white/10 w-48 p-1.5 rounded-2xl shadow-2xl backdrop-blur-xl">
               {LAYOUTS.map((l) => (
                  <DropdownMenuItem 
                    key={l.type} 
                    onClick={() => handleLayoutSelect(l.type)}
                    className="flex items-center gap-3 px-3 py-2 rounded-xl focus:bg-white/5 text-secondaryText focus:text-white cursor-pointer"
                  >
                    {l.icon}
                    <span className="text-xs font-medium">{l.label}</span>
                    {slide.layoutType === l.type && <Check className="size-3 ml-auto text-indigo-500" />}
                  </DropdownMenuItem>
               ))}
            </DropdownMenuContent>
         </DropdownMenu>

          <button 
            onClick={() => aiRegenMut.mutate("Regenerate this slide completely with more professional content and more detail")}
            disabled={aiRegenMut.isPending}
            title="Regenerate with AI"
            className="p-2 rounded-xl bg-bgDark1 border border-white/10 text-secondaryText hover:text-white hover:bg-white/5 transition-all shadow-xl disabled:opacity-50"
          >
             <Wand2 className={`size-3.5 ${aiRegenMut.isPending ? 'animate-spin' : ''}`} />
          </button>
      </div>

      {/* Slide Canvas Wrapper */}
      <div 
        id={`slide-editor-${index}`}
        className={`group relative rounded-3xl overflow-hidden shadow-[0_32px_64px_-12px_rgba(0,0,0,0.8)] border transition-all duration-500 ${
          isActive ? 'border-indigo-500/40 ring-1 ring-indigo-500/20' : 'border-white/5'
        }`}
      >
         {/* Main Rendered Slide with In-Place Editing */}
         <SlidePreview 
           slide={slide as any} 
           isFullscreen={false} 
           template={template} 
           onUpdate={(data) => contentMut.mutate(data)}
           onRegenerateImage={(prompt) => imgRegenMut.mutate(prompt)}
           onRegenerateImageAuto={() => {
             const autoPrompt = `${slide.title} - ${slide.content.slice(0, 100)}`
             imgRegenMut.mutate(autoPrompt)
           }}
           onDeleteImage={() => imgDeleteMut.mutate()}
           isUpdatingImage={imgRegenMut.isPending || imgDeleteMut.isPending}
         />

         {/* New Slide Creation, Deletion, Layout or AI Loading Overlay */}
         {(slide.id.startsWith('temp-') || deleteMut.isPending || layoutMut.isPending || aiRegenMut.isPending || isAiEditing) && (
           <div className="absolute inset-0 z-[100] flex items-center justify-center bg-black/40 backdrop-blur-md animate-in fade-in duration-300">
             <div className="flex flex-col items-center gap-4">
               <div className="h-12 w-12 rounded-full bg-indigo-500/20 flex items-center justify-center border border-indigo-500/30 relative">
                 <RefreshCw className="h-6 w-6 text-indigo-400 animate-spin" />
                 <div className="absolute inset-0 rounded-full bg-indigo-500/10 blur-xl animate-pulse" />
               </div>
               <p className="text-[10px] font-black text-white uppercase tracking-[0.2em] bg-indigo-600 px-4 py-1.5 rounded-full shadow-2xl">
                 {deleteMut.isPending ? 'Deleting Slide...' : 
                  layoutMut.isPending ? 'Updating Layout...' : 
                  aiRegenMut.isPending ? 'Regenerating Slide...' :
                  isAiEditing ? 'AI is updating slide...' :
                  'Creating Slide...'}
               </p>
             </div>
           </div>
         )}
         
         {/* AI Selection Toolbar */}
         {isActive && selection.text && (
            <TextSelectionToolbar 
              selectionRect={selection.rect}
              selectedText={selection.text}
              onAskAI={(prompt) => aiPartialMut.mutate(prompt)}
              onClose={() => window.getSelection()?.removeAllRanges()}
            />
         )}
      </div>

      {/* Delete/Options button top right */}
      <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
         <DropdownMenu>
            <DropdownMenuTrigger asChild>
               <button className="p-2 rounded-lg bg-black/40 backdrop-blur-md border border-white/10 text-white/40 hover:text-white transition-colors">
                  <MoreVertical className="size-4" />
               </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-bgDark1 border-white/10 w-fit min-w-0 p-0.5 rounded-xl shadow-2xl backdrop-blur-xl flex flex-col items-center">
               <DropdownMenuItem 
                 onClick={() => {
                   // Focusing title for rename
                   const el = document.getElementById(`slide-title-${slide.id}`)
                   el?.focus()
                 }}
                 className="flex items-center justify-center size-8 rounded-lg focus:bg-white/5 text-secondaryText focus:text-white cursor-pointer mb-0.5"
                 title="Rename"
               >
                  <Edit2 className="size-3.5" />
               </DropdownMenuItem>
               <DropdownMenuItem 
                 onClick={() => setShowDeleteConfirm(true)}
                 className="flex items-center justify-center size-8 rounded-lg focus:bg-red-500/10 text-red-400 focus:text-red-400 cursor-pointer"
                 title="Delete Slide"
               >
                  <Trash2 className="size-3.5" />
               </DropdownMenuItem>
            </DropdownMenuContent>
         </DropdownMenu>
      </div>

      <AlertDialog open={showDeleteConfirm} onOpenChange={setShowDeleteConfirm}>
        <AlertDialogContent className="bg-bgDark1 border-white/10">
          <AlertDialogHeader>
            <AlertDialogTitle className="text-white">Delete this slide?</AlertDialogTitle>
            <AlertDialogDescription className="text-secondaryText text-sm">
              This action cannot be undone. All content on this slide will be permanently removed.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="bg-white/5 border-white/10 text-white hover:bg-white/10">Cancel</AlertDialogCancel>
            <AlertDialogAction 
              onClick={() => deleteMut.mutate()}
              className="bg-red-600 hover:bg-red-700 text-white border-none"
            >
              {deleteMut.isPending ? 'Deleting...' : 'Delete Slide'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Add Slide button below */}
      <div className="absolute -bottom-8 left-1/2 -translate-x-1/2 flex items-center gap-2 opacity-0 hover:opacity-100 transition-opacity group">
         <button className="p-1 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-secondaryText hover:text-white">
            <Plus className="size-3" />
         </button>
         {!isImported && (
           <button className="p-1 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-secondaryText hover:text-white">
              <Wand2 className="size-3" />
           </button>
         )}
         <button className="p-1 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-secondaryText hover:text-white">
            <Layout className="size-3" />
         </button>
      </div>
    </div>
  )
}
