/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerPresentationIdRouteImport } from './routes/viewer.$presentationId'
import { Route as PresentationsPresentationIdRouteImport } from './routes/presentations.$presentationId'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as DashboardWorkspaceRouteImport } from './routes/_dashboard.workspace'
import { Route as DashboardWebRouteImport } from './routes/_dashboard.web'
import { Route as DashboardTrashRouteImport } from './routes/_dashboard.trash'
import { Route as DashboardTemplatesRouteImport } from './routes/_dashboard.templates'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardImportRouteImport } from './routes/_dashboard.import'
import { Route as TemplatesTemplateIdCustomizeRouteImport } from './routes/templates.$templateId.customize'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerPresentationIdRoute = ViewerPresentationIdRouteImport.update({
  id: '/viewer/$presentationId',
  path: '/viewer/$presentationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsPresentationIdRoute =
  PresentationsPresentationIdRouteImport.update({
    id: '/presentations/$presentationId',
    path: '/presentations/$presentationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebRoute = DashboardWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const TemplatesTemplateIdCustomizeRoute =
  TemplatesTemplateIdCustomizeRouteImport.update({
    id: '/templates/$templateId/customize',
    path: '/templates/$templateId/customize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/import': typeof DashboardImportRoute
  '/settings': typeof DashboardSettingsRoute
  '/templates': typeof DashboardTemplatesRoute
  '/trash': typeof DashboardTrashRoute
  '/web': typeof DashboardWebRoute
  '/workspace': typeof DashboardWorkspaceRoute
  '/api/inngest': typeof ApiInngestRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/viewer/$presentationId': typeof ViewerPresentationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$templateId/customize': typeof TemplatesTemplateIdCustomizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/import': typeof DashboardImportRoute
  '/settings': typeof DashboardSettingsRoute
  '/templates': typeof DashboardTemplatesRoute
  '/trash': typeof DashboardTrashRoute
  '/web': typeof DashboardWebRoute
  '/workspace': typeof DashboardWorkspaceRoute
  '/api/inngest': typeof ApiInngestRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/viewer/$presentationId': typeof ViewerPresentationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$templateId/customize': typeof TemplatesTemplateIdCustomizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/_dashboard/import': typeof DashboardImportRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/templates': typeof DashboardTemplatesRoute
  '/_dashboard/trash': typeof DashboardTrashRoute
  '/_dashboard/web': typeof DashboardWebRoute
  '/_dashboard/workspace': typeof DashboardWorkspaceRoute
  '/api/inngest': typeof ApiInngestRoute
  '/presentations/$presentationId': typeof PresentationsPresentationIdRoute
  '/viewer/$presentationId': typeof ViewerPresentationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$templateId/customize': typeof TemplatesTemplateIdCustomizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/import'
    | '/settings'
    | '/templates'
    | '/trash'
    | '/web'
    | '/workspace'
    | '/api/inngest'
    | '/presentations/$presentationId'
    | '/viewer/$presentationId'
    | '/api/auth/$'
    | '/templates/$templateId/customize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/import'
    | '/settings'
    | '/templates'
    | '/trash'
    | '/web'
    | '/workspace'
    | '/api/inngest'
    | '/presentations/$presentationId'
    | '/viewer/$presentationId'
    | '/api/auth/$'
    | '/templates/$templateId/customize'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/about'
    | '/contact'
    | '/_dashboard/import'
    | '/_dashboard/settings'
    | '/_dashboard/templates'
    | '/_dashboard/trash'
    | '/_dashboard/web'
    | '/_dashboard/workspace'
    | '/api/inngest'
    | '/presentations/$presentationId'
    | '/viewer/$presentationId'
    | '/api/auth/$'
    | '/templates/$templateId/customize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ApiInngestRoute: typeof ApiInngestRoute
  PresentationsPresentationIdRoute: typeof PresentationsPresentationIdRoute
  ViewerPresentationIdRoute: typeof ViewerPresentationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TemplatesTemplateIdCustomizeRoute: typeof TemplatesTemplateIdCustomizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$presentationId': {
      id: '/viewer/$presentationId'
      path: '/viewer/$presentationId'
      fullPath: '/viewer/$presentationId'
      preLoaderRoute: typeof ViewerPresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$presentationId': {
      id: '/presentations/$presentationId'
      path: '/presentations/$presentationId'
      fullPath: '/presentations/$presentationId'
      preLoaderRoute: typeof PresentationsPresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workspace': {
      id: '/_dashboard/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/web': {
      id: '/_dashboard/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof DashboardWebRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/trash': {
      id: '/_dashboard/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/templates': {
      id: '/_dashboard/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/import': {
      id: '/_dashboard/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/templates/$templateId/customize': {
      id: '/templates/$templateId/customize'
      path: '/templates/$templateId/customize'
      fullPath: '/templates/$templateId/customize'
      preLoaderRoute: typeof TemplatesTemplateIdCustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardWebRoute: typeof DashboardWebRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardImportRoute: DashboardImportRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardWebRoute: DashboardWebRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ApiInngestRoute: ApiInngestRoute,
  PresentationsPresentationIdRoute: PresentationsPresentationIdRoute,
  ViewerPresentationIdRoute: ViewerPresentationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TemplatesTemplateIdCustomizeRoute: TemplatesTemplateIdCustomizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
